### PR TITLE
Use PSR-4 autoloading

### PR DESCRIPTION
**Pull request by szepeviktor**
Please be modern :)

@jeherve

### CODE REVIEW

**Comment by jeherve** [comment]
Thanks for the PR. :) This package is still a work in progress, and is developed in our monorepo here:
https://github.com/Automattic/jetpack/pull/16657

**Comment by szepeviktor** [comment]
Okay.

**Comment by szepeviktor** [comment]
Many maintainers put `[READ-ONLY]` in the repository description and direct contributors to the monorepo in the README.

**Comment by szepeviktor** [comment]
> This repository is a mirror,

Maybe we can be more precise...

**Comment by szepeviktor** [comment]
"[READ ONLY] Subtree split of the Illuminate Database component (see laravel/framework)"

https://github.com/illuminate/database

**Comment by jeherve** [comment]
That's a good idea. I've added it.

**Comment by szepeviktor** [comment]
Thank you.

> This repository is a mirror

Could you use the _subtree split_ phrase?

**Comment by jeherve** [comment]
Since this doesn't quite use git subtrees, I'll refrain from using that wording since it could create some more confusion.

**Pull request closed without merging**
